### PR TITLE
Add SecureTransport based crypto backend using SecItemImport

### PR DESCRIPTION
**Pull request by keithduncan**
Allows for libssh2 to use the OS X native crypto libraries, replacing openssl.

There is no public BigNum library in OS X, so this adds the `CCBigNum` private header :grimacing: 
- [x] Random data function
- [x] Hash functions
  - [x] sha1
  - [x] md5
- [x] HMAC
  - [x] sha1
  - [x] md5
- [x] asymmetric encryption
  - [x] RSA
    - [x] create
      - [x] raw
      - [x] pem pkcs#1 plain
      - [x] der pkcs#1 plain
      - [x] pem pkcs#8 plain
      - [x] der pkcs#8 plain
      - [x] pem pkcs#1 cipher
      - [x] pem pkcs#8 cipher
      - [x] der pkcs#8 cipher
    - [x] sign
    - [x] verify
      - [x] convert private -> public
  - [x] DSA
    - [x] create
      - [x] raw
      - [x] pem pkcs#1 plain
      - [x] der pkcs#1 plain
      - [ ] pem pkcs#8 plain
      - [ ] der pkcs#8 plain
      - [x] pem pkcs#1 cipher
      - [x] pem pkcs#8 cipher
      - [x] der pkcs#8 cipher
    - [x] sign
    - [x] verify
      - [x] convert private -> public
- [x] symmetric encryption
  - [x] AES
  - [x] AES CTR, not available in the `CCryptorRef` API
  - [x] Blowfish
  - [x] RC4
  - [x] CAST
  - [x] 3DES
- [x] BigNum

### CODE REVIEW

**Comment by Therzok** [comment]
Is this pull request meant to target this repo? Probably it was meant to target upstream?

**Comment by keithduncan** [comment]
> Is this pull request meant to target this repo?

Yep, this gives me a staging area before I open one for upstream too

**Comment by phatblat** [comment]
I'm excited to see this in progress! We are hoping to drop OpenSSL as a dependency from ObjectiveGit as libgit2 recently switched to SecureTransport on Apple platforms. libssh2 is the only library still using it.

Do you foresee any issues with these changes on iOS?

**Comment by keithduncan** [comment]
> Do you foresee any issues with these changes on iOS?

Unfortunately this still uses the Security.framework private bignum API, which would not be approved for the app store. I’ve received advice on the libssh2 mailing list that it might be possible to replace this with public API RSA operations. I believe the WinCNG uses a similar trick to workaround not having a bignum library, but I haven’t had time to look into it yet.

The other issue is that the private key -> public key conversion functions use `SecKeyGetCSSMKey` to synthesise the public key from the private key: all the necessary fields are there it’s just a different format, it’s always struck me as ridiculous that you’d have to store and provide the public key separately when you already _have_ the private key. This function doesn’t exist on iOS and its use would have to be removed.

**Comment by ihnorton** [comment]
@keithduncan any objection if I have a go at updating this and addressing the bignum issue via the WinCNG trick? Obviously will previous your authorship (might squash history down a bit, if I get far enough along for a PR). Thanks.

**Comment by keithduncan** [comment]
@ihnorton please feel free and give me a shout if you need any help with that, sorry I haven’t had the time to come back to this but I’d love to see it finished and merged upstream.

**Comment by ihnorton** [comment]
Thanks, I got the branch rebased, updated, and compiling [here](https://github.com/ihnorton/libssh2/tree/ihn/sf). It passes the tests, once I modified the `test_ssh2_fixture` script to specify a useable set of ciphers to sshd. Previously got session initialization errors (`-5`) because there was no common cipher supported by both libssh2 and sshd during kex. Not sure if the sshd defaults changed in OS10.11 or what.

I'm going to have a look at the bignum issue over the next few evenings. I guess my biggest question is: how did you test this when you were working on it? The tests seem limited. (I'm hoping there is some out-of-tree API test suite or something that I missed...)

**Comment by keithduncan** [comment]
> The tests seem limited. (I'm hoping there is some out-of-tree API test suite or something that I missed...)

Yep, I used https://github.com/keithduncan/libssh2-securetransport-tests

**Comment by Keno** [comment]
@ihnorton I ran that testsuite with your branch. It crashed. Since all discussion is here, I'll record the error for future reference:
```
Test Case '-[libssh2_securetransport_rsa test_DER_PKCS1_Plain]' started.
xctest(71691,0x7fff7cd44000) malloc: *** error for object 0x1002acbf8: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```
in `CFDataRef signatureData = SecTransformExecute(transform, NULL);`

**Comment by Keno** [comment]
Found it. That was simple. Just a simple double free:
```diff
diff --git a/configure.ac b/configure.ac
index 4bf5e96..53b8d47 100644
--- a/configure.ac
+++ b/configure.ac
@@ -178,7 +178,7 @@ if test "$found_crypto" = "none" && test "$use_securetransport" != "no"; then
 fi
 if test "$cv_framework_securetransport" = "yes"; then
   AC_DEFINE([LIBSSH2_SECURETRANSPORT], 1, [Use SecureTransport])
-  LIBS="$LIBS -framework Security"
+  LIBS="$LIBS -framework Security -framework CoreFoundation"
   found_crypto=securetransport
 
   AC_CHECK_FUNCS(SecRandomCopyBytes)
diff --git a/src/securetransport.c b/src/securetransport.c
index 2d69cae..f2b407a 100644
--- a/src/securetransport.c
+++ b/src/securetransport.c
@@ -1629,7 +1629,6 @@ int _libssh2_pub_priv_keyfile(LIBSSH2_SESSION *session,
 
   error = _libssh2_pub_priv_key(session, method_ref, method_len_ref, pubkeydata_ref, pubkeydata_len_ref, key);
 
-  CFRelease(key);
   return error;
 }
 
@@ -1661,7 +1660,6 @@ int _libssh2_pub_priv_keyfilememory(LIBSSH2_SESSION *session,
 
   cleanup:
   {
-    CFRelease(key);
     CFRelease(keyData);
   }
 ```
Test suite passes now. Will take a crack at the bignum problem.

**Comment by Keno** [comment]
Unfortunately the WinCNG trick won't work unmodified because the Security framework imposes a maximum keysize:
```
		if(keySize > rsaMaxPubExponentSize()) {
			badKey = true;
			rsaMiscDebug("rawCssmKeyToRsa: pub exponent size exceeded"); 
		}
```
I'll try using decryption instead. Hopefully the private key import does not have the same limitations.
Also for future reference, the following command is super useful in debugging key import errors:
```
sudo dtrace -n 'security_debug83488:Security:secdebug_internal:log { printf("%s %s %s", execname, copyinstr(arg0), copyinstr(arg1)) }'
```

**Comment by Keno** [comment]
Intermediate update: The existing code (with minor modifications) can be made to almost work by setting `RSAMaxPublicExponent` in `com.apple.security.plist` and restarting the security server:
```
sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.securityd.plist
sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.securityd.plist
```
Latest failure after that is:
```
[libssh2] 0.874524 Transport: Packet type 33 received, length=754
[libssh2] 0.874529 Transport: Looking for packet of type: 33
[libssh2] 0.874544 Key Ex: Server's MD5 Fingerprint: a0:90:21:52:25:7a:06:7f:b9:7b:52:ce:fa:a6:93:7f
[libssh2] 0.874555 Key Ex: Server's SHA1 Fingerprint: 86:ad:b2:21:33:60:65:3d:9a:29:86:de:22:99:da:18:cc:ba:d3:ac
[libssh2] 0.895649 Failure Event: -11 - Unable to verify hostkey signature
[libssh2] 0.895664 Failure Event: -8 - Unrecoverable error exchanging keys
[libssh2] 0.895668 Failure Event: -8 - Unable to exchange encryption keys
```

**Comment by Keno** [comment]
I finished the `SecKeyEncrypt` based version, which works well, but only if `RSAMaxPublicExponent` is adjusted. Unfortunately using the decryption functions instead doesn't work, because it needs the primes (which we don't have) to speed up the computation. So unless someone knows how to locally adjust `RSAMaxPublicExponent`, I'm out of ideas.

**Comment by tiennou** [comment]
I'm investigating this too (coming from libgit2), and I have a [branch](https://github.com/tiennou/libssh2/tree/secure-transport) with a hard revert (eg. rebased) of the BigNum changes, a tweak to the "from_memory implementation" and support for more SHA stuff.

I have been looking for solutions to the BigNum problem :
- the Accelerate.framework has a 1024 bits max BigNum implementation [here](https://developer.apple.com/library/mac/documentation/Performance/Conceptual/vecLib/) but I don't know if it's feasible to extend it to arbitrary BigNums.
- There's a BSD-licensed BigNum implementation [here](https://github.com/PascalLG/biginteger-objc).

**Comment by tiennou** [comment]
Oh, and so it's not forgotten : the non-optimizable `memset_s` is available in `<string.h>` and can be used for LIBSSH2_CLEAR_MEMORY, but it's a C11 extension, and I don't know where libssh2 stands w.r.t to C standard compatibility.

**Comment by keithduncan** [comment]
I’m planning to look at the API diffs in macOS Sierra to see if it’s possible to revive this

**Pull request closed without merging**
